Adding page design
Odile078/Kmarketer-site pull request #1
Opened 2022-10-06 08:03 UTC by Odile078

Hi, your reviews would be appreciated

2022-10-06 09:13 UTC, Nkaka23dev reviewed
Try to follow BEM

2022-10-06 09:13 UTC, Nkaka23dev commented on css/index.css
> +ul{
This is not BEM

2022-10-06 09:13 UTC, Nkaka23dev commented on css/index.css
> +a{
This is not BEM

2022-10-06 09:13 UTC, Nkaka23dev commented on css/index.css
> +h1,h2,h3,h4,h5,p{
This is not BEM

2022-10-06 09:13 UTC, Nkaka23dev commented on css/index.css
> +button{
This is not BEM

2022-10-06 09:13 UTC, Nkaka23dev commented on css/index.css
> +div{
This is not BEM

2022-10-06 09:13 UTC, Nkaka23dev commented on css/index.css
> +.icon-list__item .icon-list__icon{
This is not BEM

2022-10-06 09:13 UTC, Nkaka23dev commented on css/index.css
> +.icon-list__item:hover .icon-list__icon{
This is not BEM

2022-10-06 09:13 UTC, Nkaka23dev commented on css/index.css
> +.section-wrapper > * + *{
This is not BEM

2022-10-06 09:13 UTC, Nkaka23dev commented on css/index.css
> +.card > * + *{
Not BeM

2022-10-06 09:13 UTC, Nkaka23dev commented on css/index.css
> +.card__header >* + *{
This is nor BEM

2022-10-06 09:13 UTC, Nkaka23dev commented on css/index.css
> +.card__footer .card__img{
This is not BEM

2022-10-06 09:13 UTC, Nkaka23dev commented on css/index.css
> +.services__header > * + *{
This isn not BEM

2022-10-06 09:13 UTC, Nkaka23dev commented on css/index.css
> +.team .card{
Not BEM

2022-10-06 09:13 UTC, Nkaka23dev commented on css/index.css
> +.team .card__img{
NOT BEM

2022-10-06 09:13 UTC, Nkaka23dev commented on css/index.css
> +.contact__action .button{
This is not BEM

2022-10-06 09:13 UTC, Nkaka23dev commented on css/index.css
> +.form__wrapper .form__group{
Not BEM

2022-10-06 09:13 UTC, Nkaka23dev commented on css/index.css
> +.form__wrapper .form__input{
This is not BEM

2022-10-06 09:44 UTC, alain-kubwayo requested changes
### Great job applying BEM to your project.
I have added a couple of comments for things to improve on.

2022-10-06 09:44 UTC, alain-kubwayo commented on index.html
> +                <svg
You can give the `svg` a class to stay consistent with BEM. Something like `card__icon` would work.

2022-10-06 09:44 UTC, alain-kubwayo commented on index.html
> +                <svg
Same here.

2022-10-06 09:44 UTC, alain-kubwayo commented on index.html
> +                <svg
Here as well.

2022-10-06 09:44 UTC, alain-kubwayo commented on index.html
> +                <svg
Same here.

2022-10-06 09:44 UTC, alain-kubwayo commented on index.html
> +      <section id="services " class="services">
code formatting issue. format the id nicely for readability purpose.

2022-10-06 09:44 UTC, alain-kubwayo commented on index.html
> +      <section id="services " class="services">
Are you using `id's` to add any particular functionality? If not, they are not needed since you can target elements by class names in BEM.

2022-10-06 09:44 UTC, alain-kubwayo commented on index.html
> +            /> -->
I would delete this if I'm not entirely using it.

2022-10-06 09:44 UTC, alain-kubwayo commented on index.html
> +      <section id="clients" class="clients">
Same here with the id.

2022-10-06 09:44 UTC, alain-kubwayo commented on index.html
> +              <svg
Missing class on the `svg`

2022-10-06 09:44 UTC, alain-kubwayo commented on index.html
> +              <svg
Here as well. (They are optional but make your code more consistent)

2022-10-06 09:44 UTC, alain-kubwayo commented on index.html
> +              <svg
Here as well.

2022-10-06 09:44 UTC, alain-kubwayo commented on index.html
> +              <svg
Missing (optional) class here.

2022-10-06 09:44 UTC, alain-kubwayo commented on index.html
> +      <section id="team" class="team">
Same with the `id` too. Keep it only if you're using it for a particular functionality, otherwise you don't really need it.

2022-10-06 09:44 UTC, alain-kubwayo commented on index.html
> +                <svg
Missing class on `svg's`

2022-10-06 09:44 UTC, alain-kubwayo commented on index.html
> +      <section id="contact" class="contact">
Same question with `id` here.

2022-10-07 05:20 UTC, alain-kubwayo requested changes
### Good job implementing the requested changes.
Some small adjustments to be made. Refer to the comments

2022-10-07 05:20 UTC, alain-kubwayo commented on index.html
> +            /> -->
You should consider cleaning up your code by removing this commented out piece of code.

2022-10-07 05:20 UTC, alain-kubwayo commented on index.html
> +              class="sercvices__img"
I think `sercvices__img` is a typo. Did you mean `services__img`?

2022-10-07 05:20 UTC, alain-kubwayo commented on index.html
> +              <svg
You forgot to add a class to these `svg's`

2022-10-07 05:20 UTC, alain-kubwayo commented on css/index.css
> +    align-content: center;*/
Clean your code by removing the unused styles.

2022-10-07 05:20 UTC, alain-kubwayo commented on css/index.css
> +    /* max-width: 36rem; */
Same here.

2022-10-07 05:20 UTC, alain-kubwayo commented on css/index.css
> +        max-width: 36rem;
Here as well.

2022-10-07 09:45 UTC, Nkaka23dev reviewed
I requested other changes , work on it.

2022-10-07 09:45 UTC, Nkaka23dev commented on css/index.css
> +.card__header >* + *{
This is not BEM ypou need to change it.

2022-10-07 09:45 UTC, Nkaka23dev commented on index.html
> +          <div>
Please give this a name or remove it if it is not usefull

2022-10-07 09:45 UTC, Nkaka23dev commented on index.html
> +          <div>
Every element should have a name

2022-10-07 10:11 UTC, Nkaka23dev commented on css/index.css
> +.hero__wrapper> *{
This also is not BEM

2022-10-07 10:20 UTC, Nkaka23dev approved these changes
LGTM! Good Job.

2022-10-07 10:28 UTC, alain-kubwayo approved these changes
### Looks good

2022-10-07 13:03 UTC, Morrism1 approved these changes
Good Job! 🚀

2022-10-07 17:08 UTC, merged